### ISSUE TITLE
HA 2021.6: maxBarThickness is deprecated

### ISSUE THREAD

**Issue by Mariusthvdb** [Yevgenium/lovelace-weather-card-chart#57]
from ha 2021.6 on:

<img width="609" alt="Schermafbeelding 2021-05-31 om 11 32 13" src="https://user-images.githubusercontent.com/33354141/120184484-53bc1600-c211-11eb-963f-75a7d1f356c0.png">

according to Discord #beta this has to do with a bump in `chart.js`

tried to solve it locally by adding
```
          {
           maxBarThickness: 15,
          },
```
under datasets, and this makes the warning disappear. (as does taking out the line completely without replacing it......)
cant say if this is a correct fix, because nothing's happening at all...
please have a look?

**Comment by inthehoose** [comment]
I added barThickness and maxBarThickness attributes here to my local file to get the precipitation bars to appear again:

```
          {
            label: this.ll('precip'),
            type: 'bar',
            data: precip,
            yAxisID: 'PrecipAxis',
            maxBarThickness: 15,
            barThickness: 12,
          },
```

**Comment by inthehoose** [comment]
Clear your browser cache so the updated .js file can be downloaded.

**Comment by Mariusthvdb** [comment]
I know how to update a custom card..... ;-)

its just that I wonder what the change actually does (I see no difference )

**Comment by Mariusthvdb** [comment]
will close, as the latest edits and now PR #60 has this fixed.
