### ISSUE TITLE
HA 20212.7 No more Chart....

### ISSUE THREAD

**Issue by Mariusthvdb** [Yevgenium/lovelace-weather-card-chart#59]
as HA changed its Charts, this is now no longer functional and showing the Chart card without Chart

<img width="486" alt="Schermafbeelding 2021-07-02 om 09 55 50" src="https://user-images.githubusercontent.com/33354141/124241118-c162a700-db1b-11eb-9f23-682c5622b8aa.png">

error in inspector:

`Cannot read property 'forEach' of undefined`
in:
```
          var meta = chartInstance.controller.getDatasetMeta(2);
            meta.data.forEach(function (bar, index) {
              var data = (Math.round((chartInstance.data.datasets[2].data[index]) * 10) / 10).toFixed(1);
              ctx.fillText(data, bar._model.x, bar._model.y - 5);
            });
```
called by:
`<ha-chart-base hass="[[_hass]]" data="[[ChartData]]"></ha-chart-base>`

resource file in HA code:
https://github.com/home-assistant/frontend/blob/dev/src/components/chart/ha-chart-base.ts

**Comment by redwngsrul** [comment]
Getting a different ERROR message in the log, but it seems to have the same result, i.e. no chart displayed.

```
Logger: frontend.js.latest.202107070
Source: components/system_log/__init__.py:190
First occurred: 11:18:00 PM (6 occurrences)
Last logged: 11:41:38 PM

https://99.75.76.135:8123/local/weather-card-chart.js:307:16 TypeError: this.weatherObj.attributes is undefined
:0:0 ResizeObserver loop completed with undelivered notifications.
```

![image](https://user-images.githubusercontent.com/33060660/124859118-48c97380-df7d-11eb-9655-95baf447b2b5.png)

**Comment by redwngsrul** [comment]
Getting a different ERROR message in the log but seems to have the same result, i.e. no chart displayed.

```
Logger: frontend.js.latest.202107070
Source: components/system_log/__init__.py:190
First occurred: 11:18:00 PM (6 occurrences)
Last logged: 11:41:38 PM

https://[myHASS]/local/weather-card-chart.js:307:16 TypeError: this.weatherObj.attributes is undefined
:0:0 ResizeObserver loop completed with undelivered notifications.
```
![image](https://user-images.githubusercontent.com/33060660/124859118-48c97380-df7d-11eb-9655-95baf447b2b5.png)

**Comment by override80** [comment]
![image](https://user-images.githubusercontent.com/43748388/124903864-b066d980-dfe4-11eb-98d0-025aaa5d203e.png)

Don't know if this is relevant, but I see this in firefox web developers tools

**Comment by Dreffi88** [comment]
The problem remains with core-2021.7.1.

**Comment by Mariusthvdb** [comment]
of course it does, why would you think updating HA fixed this? It is an issue in the custom card code for charts no longer being compatible with HA...

**Comment by koying** [comment]
Same here :(
Will dig into it...

**Comment by Mariusthvdb** [comment]
See Bram's remark on what changed in Ha : https://discord.com/channels/330944238910963714/351047592588869643/863075287830757397

**Comment by koying** [comment]
See https://github.com/koying/lovelace-weather-card-chart/tree/chartjs3 for a working fix
Please test, probably still some issues to be fixed

**Comment by tomlut** [comment]
Working for me.

**Comment by gopheridze** [comment]
> See https://github.com/koying/lovelace-weather-card-chart/tree/chartjs3 for a working fix
> Please test, probably still some issues to be fixed

Works in Chrome, but doesn't in Safari

**Comment by tomlut** [comment]
FYI I'm using Firefox.

**Comment by Dreffi88** [comment]
For me it is working in Safari (iOS and MacOS).

**Comment by fancygaphtrn** [comment]
I updated my fork to support HA 2021-7-6.  
https://github.com/fancygaphtrn/lovelace-weather-card-chart.

**Comment by Mariusthvdb** [comment]
<img width="383" alt="Schermafbeelding 2021-07-12 om 00 20 51" src="https://user-images.githubusercontent.com/33354141/125211503-1f735500-e2a7-11eb-8ba8-b768653e76d3.png">

<img width="377" alt="Schermafbeelding 2021-07-12 om 00 22 19" src="https://user-images.githubusercontent.com/33354141/125211522-3fa31400-e2a7-11eb-83c3-c39b6d75a360.png">


working in Safari and Chrome.

magic, thanks @koying 


hope you can fix the colors too..shall I keep open to await that.

btw, are you going to create a PR here, so its easier to spot the changes? had to check line by line in my own file, and that wasn't too easily done I must admit....

**Comment by koying** [comment]
Yeah, I couldn't understand how colors are "auto-assigned", so I hardcoded them.
I still see an issue in that, with no precipitations, "0.0" is displayed while it wasn't before.
![image](https://user-images.githubusercontent.com/164740/125242680-4f454b80-e2ed-11eb-86c5-3acc0757234d.png)


But good enough for a PR, I guess

**Comment by koying** [comment]
PR created: https://github.com/Yevgenium/lovelace-weather-card-chart/pull/60
